root: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:vue/vue3-recommended
  - '@vue/eslint-config-typescript'
  - '@vue/eslint-config-prettier/skip-formatting'
  - plugin:prettier/recommended
  - prettier

parser: vue-eslint-parser

parserOptions:
  project: ./tsconfig.app.json
  extraFileExtensions: [.vue]
  parser:
    js: espree
    ts: typescript-eslint-parser-for-extra-files
    vue: vue-eslint-parser

overrides:
  - files: ['*.js', '*.cjs', '*.mjs', '*.jsx']
    extends:
      - plugin:@typescript-eslint/disable-type-checked
  - files: ['vite.config.ts']
    parserOptions:
      project: ./tsconfig.node.json
