# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
semi: false
singleQuote: true
quoteProps: consistent
trailingComma: none
bracketSameLine: true
arrowParens: avoid
printWidth: 120
tabWidth: 2
endOfLine: lf
